/// <reference types="@raycast/api">

/* eslint-disable @typescript-eslint/no-empty-interface */

// This file is auto-generated by `npx ray build env` and
// should NOT be edited manually.

interface Preferences {}

interface ExtensionPreferences {}

interface Arguments {}
